name: CI

on:
  push:
    branches: main
  pull_request:
    branches: main
  schedule:
    # workwaround for cannot set timezone, cron will start on Asia/Shanghai 03:15
    - cron: "15 19 * * *"
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Whether to deploy to hf-pages branch'
        required: true
        default: '0'

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build
        run: ./generate.sh
      - name: Deploy
        if: ${{ github.event_name == 'schedule' || github.event.inputs.deploy == '1' }}
        run: |
          # update hf-pages
          git clone https://github.com/${{ github.repository }}.git hf-pages -b hf-pages --depth 1 --single-branch
          cp -rf dist/* hf-pages
          # push to hf-pages
          cd hf-pages
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "$(date '+%Y-%m-%d %H:%M:%S')" || true
          git push https://${{ github.repository_owner }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git hf-pages
